# datasource
spring:
  datasource:
    url: jdbc:mysql://dev.database.guoing.com:3306/pumpkin_tracking?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&maxReconnects=10&useSSL=false
    username: doras_all_dev
    password: vDik8!u&Rme59AXM
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    rest:
      uris: es-cn-0pp110o52000d5o0v.public.elasticsearch.aliyuncs.com:9200
      username: elastic
      password: PumpkinES2o19

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.itheima.elasticsearchdemo.domain

logging:
  level:
    root: info